### PR TITLE
.NETStandard compat

### PR DESCRIPTION
**Pull request by sebandraos**
Removes .net4.0 support and runs for .NETStandard.
[Issue] Currently can't share the assembly info between PropertyChanged.Fody and PropertyChanged. It creates a duplicate definition as .NETStandard projects have everything defined implicitly. Workaround is just to manually update the version numbers in PropertyChanged separately.

### CODE REVIEW

**Comment by sebandraos** [comment]
So this is failing because it can't find the right version of MSBuild. This will only build with MSBuild 15+ which is now much more tightly associated with an install of VS2017 and located in its install location. I am trying to solve this same issue in my own CI pipeline so will update here is I find a fix.

**Comment by SimonCropp** [comment]
i changed appveyor to be 2017.  do a touch on a file to force a new build

**Comment by SimonCropp** [comment]
Out of curiosity why not netstandard 1.4?

**Comment by sebandraos** [comment]
Only because that's what you had before. Personally I always like aiming as low as possible but I appreciate that it's not necessarily worthwhile given that Fody itself targets 1.4 and this is entirely dependent on that.
The checks that are failing are now just the tests because I had to get rid of the Net40Client project. I'm not sure where that is being used or how to remove it.

**Comment by sebandraos** [comment]
The easy way to pass a test is to get rid of the one that's failing. The reason for the failure, however, is probably better handled by you, @SimonCropp , who has a better knowledge of the tests' intentions. There are a number of changes to the csproj format in the new version with .netstandard and as such things like the output path can't just be read straight from the xml as you seem to be doing.

**Comment by dansiegel** [comment]
any eta on this?

**Comment by graemechristie** [comment]
Is there anything happening with this PR ? I pulled this version down and attempted to manually build and bin-deploy. It still seems to be referencing the net452 version of Fody. If Fody.PropertyChanged is not moving to NetStandard in the near future it would be good to know so we can work on another solution ..

**Comment by wocar** [comment]
Does this PR fix this error?


> Error		Fody: An unhandled exception occurred:
> Exception:
> Referencia a objeto no establecida como instancia de un objeto.
> StackTrace:
>    en ModuleWeaver.FindCoreReferences() en C:\projects\propertychanged\PropertyChanged.Fody\MsCoreReferenceFinder.cs:línea 24
>    en ModuleWeaver.Execute() en C:\projects\propertychanged\PropertyChanged.Fody\ModuleWeaver.cs:línea 26
>    en lambda_method(Closure , Object )
>    en InnerWeaver.ExecuteWeavers() en C:\projects\fody\FodyIsolated\InnerWeaver.cs:línea 182
>    en InnerWeaver.Execute() en C:\projects\fody\FodyIsolated\InnerWeaver.cs:línea 83
> Source:
> PropertyChanged.Fody
> TargetSite:
> Void FindCoreReferences()
>

**Comment by wocar** [comment]
Any ETA on this ? @SimonCropp

**Comment by eduard1989** [comment]
Any update?

**Comment by SimonCropp** [comment]
merged manually here https://github.com/Fody/PropertyChanged/commit/d53c7c23dfd85a1726969b6ad4d978270fcdef61

**Pull request closed without merging**
