### PR TITLE
Add OnChangedMethodAttribute

### LINKED ISSUE #453: Introduce a "OnChangedMethod" attribute
```c#
class MyClass : INotifyPropertyChanged 
{
    [OnChangedMethod(nameof(OnMyPropertyChanged))]
    int MyProperty { get; set; }

    void OnMyPropertyChanged()
    {
    }
}
```
Since we have a `nameof` operator today, we could decorate the property with a "link" to the on changed method. 
This will avoid the problems with renaming, and omit the compiler warnings that `OnMyPropertyChanged` is never used. It also will allow direct navigation to the method from the property.

This attribute would be optional, for those who like to use it.
To be fully backward compatible, the weaver would only check that, if the attribute is present, the name of the method matches the desired pattern. 

#447 could then also give a hint to properly decorate the property.

### PR DESCRIPTION
**Pull request by ltrzesniewski**
Fixes #453.

This is a draft PR for now as I based it on #449 (it was easier this way, it would have caused conflicts otherwise). I'll rebase this once #449 is merged.

### CODE REVIEW

**Comment by tom-englert** [comment]
:+1:

**Comment by SimonCropp** [comment]
@ltrzesniewski still in draft?

**Comment by ltrzesniewski** [comment]
It's waiting for #449 to be merged (as it currently is based on it). I'll then rebase it and maybe add a few more unit tests.

**Comment by SimonCropp** [comment]
@ltrzesniewski do u have time to rebase this?

**Comment by ltrzesniewski** [comment]
Sure, I'll finish this, probably this weekend.

**Comment by ltrzesniewski** [comment]
Ok, I rebased and polished this thing, which means it's a bigger change now but it should be better integrated with the rest.

Stuff that changed since last time:
 - You can write `[OnChangedMethod(null)]` on a `Foo` property to disable calling the default `OnFooChanged` method (not sure if useful, but probably more useful than an error).
 - When you use `[OnChangedMethod(...)]` it's an *explicit* directive to add the call to the method, which means the call will be inserted even if there's already such a call, or if `InjectOnPropertyNameChanged` is set to `false`.

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.

thanks @tom-englert and @ltrzesniewski

**Pull request merged**
