### PR TITLE
Added TypeFilterAttribute

### PR DESCRIPTION
**Pull request by pietervp**
Added the ability to filter which types are included in the weaving process. This is done by defining assembly attributes which define Regex based filters. Those filters are matched with the Type.FullName to determine wether to include them or not in the weaving.

Motivation was a rather large project with a lot of INotifyPropertychanged classes, but only a limited amount of classes which needed the NotifyPropertyChanged weaving.

### CODE REVIEW

**Comment by SimonCropp** [comment]
what bugs have u had by injecting weaving into classes that didnt need it?

**Comment by pietervp** [comment]
I didn't necessarily had any bugs, the main reason to create this pull request was the performance impact of injecting all properties in all classes vs the classes we needed.
On my recent MacBook Pro, it took Fody almost 7 sec to build this assembly.
``` 
1>      Finished Fody 6768ms.
```

**Comment by SimonCropp** [comment]
ok i will look at merging this shortly. out of curiosity what is the perf after the filter?

**Comment by SimonCropp** [comment]
merged manually here https://github.com/Fody/PropertyChanged/commit/464dbaf9d5c4d50de55450719cb87b3012f003e0

**Comment by SimonCropp** [comment]
this should be on nuget now

**Comment by stephenhauck** [comment]
I was wondering if there is a way to verify what is having the property injected when you use filtering ...
Like I want to ONLY inject the code into the objects in a folder in my application like so 
[assembly: PropertyChanged.FilterType("MyApp.Models.")]

So how do I verify that I didn't make a mistake when setting the filter up ?

Thanks for any advice you can offer.

**Pull request closed without merging**
