### PR TITLE
DoNotCheckEquality needs to support "inherited" class attribute

### PR DESCRIPTION
**Pull request by Jaben**
I have the attribute on a base class and all derived classes should disable equality.

### CODE REVIEW

**Comment by Jaben** [comment]
@SimonCropp Sorry, I didn't finish the request the first time... my bad.

**Comment by SimonCropp** [comment]
No worries. Just bedn busy

**Comment by Jaben** [comment]
Cheers mate!

**Comment by SimonCropp** [comment]
Will deploy in a few hours

**Comment by SimonCropp** [comment]
pushed to nuget

**Comment by Jaben** [comment]
thanks again!

**Pull request merged**
