### PR TITLE
#309: static Equals not used

### LINKED ISSUE #309: static Equals not used
According to the wiki a static Equals method should be used for equality checking.
 (https://github.com/Fody/PropertyChanged/wiki/EqualityChecking)

This does not work in two cases:
1) static Equals is defined in a base class
```
public class BaseClass
{
    public static bool Equals(BaseClass first, BaseClass second) {...}
}

public class ChildClass : BaseClass
{ }

public class OtherClass : INotifyPropertyChanged
{
   public ChildClass Property { get; set; }
}
```

Result: after weaving, the setter of OtherClass.Property uses object.Equals() instead of BaseClass.Equals()

2) The class implementing the static Equals method is in another assembly
```
Assembly 1:
public class SomeClass 
{
   public static bool Equals(SomeClass first, SomeClass second) { ... }
}

Assembly 2:
public class OtherClass : INotifyPropertyChanged
{
   public SomeClass Property { get; set; }
}
```

Same result: after weaving, the setter of OtherClass.Property uses object.Equals() instead of SomeClass.Equals()

I've already fixed that and will create a PR soon.

### PR DESCRIPTION
**Pull request by jhartmann123**
Fixes #309

### CODE REVIEW

**Comment by SimonCropp** [comment]
happy to accept this as a change but not in its current form. walking up the hierarchy for every type is not ideal https://github.com/Fody/PropertyChanged/pull/310/files#diff-0475c87a808e41b1f849062b31c9a3d3R85

this type of information should be stored in TypeNode https://github.com/Fody/PropertyChanged/blob/master/PropertyChanged.Fody/TypeNode.cs on a single pass then used on all classes when injecting

**Comment by jhartmann123** [comment]
I couldn't really use TypeNode, as those are only created for the types defined in the assembly that gets currently weaved, if I'm not wrong. As I obviously also need the equality comparers for properties with types defined in other assemblies, that's a small show stopper.

Instead I'm filling the (already existing) method cache a bit more aggressivly, so the type hierarchy only has to be run down once.

Example:
```
class A : B{}
class B : C{}
class C {
   static bool Equals(...)
}
```
When looking for the static equals on A, after the method was found on C, the cache gets filled with a reference to the method for all three types A, B and C.

I hope that's a bit more to your taste :)

**Comment by jhartmann123** [comment]
Sorry, sometimes I'm an idiot and can't see the easiest solution...

Equality info gets stored in the PropertyData now - I can move it up to TypeNode if you want to. Either way - it gets loaded in one pass while filling the TypeNodes now.

**Comment by SimonCropp** [comment]
thanks. this is now deployed. although nuget might take a few hours to update its index

**Pull request merged**
