### PR TITLE
Added support for the "Do not check equality" to an entire class.

### PR DESCRIPTION
**Pull request by Jaben**
Disables equality checking for an entire class.

### CODE REVIEW

**Comment by SimonCropp** [comment]
Looks good. Thanks

**Comment by Jaben** [comment]
Thanks Simon. Any idea when the next release will go out?

**Comment by SimonCropp** [comment]
I can do a release tomorrow

**Comment by Jaben** [comment]
@SimonCropp Fantastic! :+1:

**Comment by SimonCropp** [comment]
pushed to nuget

**Pull request merged**
