### PR TITLE
Using xdt to update FodyWeaver file.

### LINKED ISSUE #113: FodyWeavers.xml not modified
PropertyChanged didn't add itself to `fodyweavers.xml` but PropertyChanging did.

I suspect the magic line that made PropertyChanging work was https://github.com/Fody/PropertyChanging/blob/master/Nuget/install.ps1#L84

### PR DESCRIPTION
**Pull request by distantcam**
Fixes #113

### CODE REVIEW

**Comment by SimonCropp** [comment]
Do we still need the project level hack when using xdt?

**Comment by distantcam** [comment]
Nope. I thought it might have been in there to clean up after older versions.

**Comment by distantcam** [comment]
Can I get this merged?

**Comment by SimonCropp** [comment]
i have been holding off on this since i want to do it in a consistent way across all the repos. so as u can see it is a bit more work than a single button click

**Pull request merged**
