### PR TITLE
BeforeAfterCheckField

### PR DESCRIPTION
**Pull request by mortengjesing**
Make it possible to check field insted of get method

### CODE REVIEW

**Comment by mortenmercell** [comment]
The solution is not perfect as it only works on the "main property" and not on the dependent properties.
The collection AlsoNotifyFor on PropertyData cotains PropertyDefinition but it need to be PropertyData instead - but it seems to be a difficult (at least for me) to implement. If someone can help to change the AlsoNotifyFor collection the it is easy to implement the solution for dependend properties also.

**Comment by SimonCropp** [comment]
Can u add some tests that verifies the actual weaving so it is clear what this pr is actually attempting

**Comment by mortengjesing** [comment]
What are your thoughts about the code?

**Comment by mortengjesing** [comment]
@SimonCropp is it still not clear - or any other thoughts?

**Comment by SimonCropp** [comment]
so i see what you are doing but i dont understand why

**Comment by mortengjesing** [comment]
We do different things in our get that should not be called during a set. The main problem is lazy loads. But it could also be a property where we return a default value if the backing field is null, but wants to know we changed it from null to new value.

**Comment by SimonCropp** [comment]
@mortengjesing i am sorry for the effort you have gone to here. but complex logic inside gets is not really a scenario i think can be handled in a way that covers all the edge cases. 

so i am closing this

**Comment by mortengjesing** [comment]
@SimonCropp I don't understand why you object to making the framework more flexible to allow it to work in more projects. We really like the basis of the framework and want to contribute to make it even stronger, and we are already in progress with more flixbility.

I don't see this as a edge case, in fact i can se that you already have a problem i current solution with "CircularProperties" where "BeforeAfterCheckField" would allow a nice solution to that.

Please reconsider to allow more flexibility to framework.

**Comment by SimonCropp** [comment]
as i said i am sorry for the effort

this project is about enabling people to simplify their models so binding can work with something like this
```
public class Person 
{        
    public string GivenNames { get; set; }
    public string FamilyName { get; set; }

    public string FullName
    {
        get
        {
            return string.Format("{0} {1}", GivenNames, FamilyName);
        }
    }
}
``

ie no code in gets and sets. 

While your PR might be valid for your use case it has not been requested by anyone for the several years it has existed. 

as for the edge cases, there are always edge cases in implementing new features, these edge cases are particularly hard to spot when coding IL. 

I am more than happy for you to fork this project and create fork your own project with more flexibility that enables your scenarios.

I will happy tweet it, advertise it on the readme of this project as a "more advanced alternative" and add it hear https://github.com/Fody/Fody#addins-list

**Pull request closed without merging**
