### PR TITLE
Properly handle PropertyChanged event raisers that return Task

### LINKED ISSUE #345: PropertyChanged.Fody + MvvmCross 6.2 = crash
Combining PropertyChanged.Fody with MvvmCross 6.2-beta results in crashing with `System.InvalidProgramException: Invalid IL code in MyApp.Core.ViewModels.LoginViewModel:set_RememberMe (bool): IL_0020: ret`

see: https://github.com/MvvmCross/MvvmCross/issues/3016
Probable Solution:  Properly handle Task-returning as well as void-returning `RaisePropertyChanged()`.

### PR DESCRIPTION
**Pull request by borbmizzet**
fixes #345

### CODE REVIEW

**Comment by SimonCropp** [comment]
the test seems to be failing

**Comment by borbmizzet** [comment]
It is succeeding on my local system every time, so I'm not sure why appveyor is failing.

**Comment by borbmizzet** [comment]
@SimonCropp Fixed it

**Comment by SimonCropp** [comment]
thanks. this should now be deployed

**Pull request merged**
